stow:
	@echo "do nothing"

unstow:
	@echo "do nothing"

init:
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

install:
	brew bundle --file=brew/brew-$(type) --all

