live_config_reload = true 

import = [ "~/.config/alacritty/themes/themes/tokyo-night-storm.toml" ]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7

[window.padding]
x = 9
y = 9

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CodeNewRoman Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CodeNewRoman Nerd Font"
style = "Regular Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

