#!/bin/sh
source $HOME/.config/sketchybar/color.sh

APPLE_ICON_SIZE=20
APPLE_Y_OFFSET=2

ICON_FONT="CodeNewRoman Nerd Font"
ICON_WEIGHT="Bold"
ICON_SIZE="14.0"
ICON_PADDING_L=9
ICON_PADDING_R=9

APPICON_FONT="sketchybar-app-font"
APPICON_WEIGHT="Regular"
APPICON_SIZE="14.0"
APPICON_PADDING_L=9
APPICON_PADDING_R=9

LABEL_FONT="SF Pro Text"
LABEL_WEIGHT="Bold"
LABEL_SIZE="13.0"
LABEL_PADDING_L=9
LABEL_PADDING_R=9

BAR_HEIGHT=32
BAR_POSITION="top"
BAR_PADDING_TOP=4
# NOTCH_WIDTH=188

DEFAULT_PADDING_L=3
DEFAULT_PADDING_R=3
BACKGROUND_HEIGHT=28
BACKGROUND_CORNER_RADIUS=15
BACKGROUND_BORDER_WIDTH=1

SPACESET_BACKGROUND_CORNER_RADIUS=15
SPACE_ICON_PADDDING_L=5
SPACE_ICON_PADDDING_R=5
SPACE_LABEL_PADDING_L=5
SPACE_LABEL_PADDING_R=5
SPACE_BACKGROUND_BORDER_WIDTH=0

ALIAS_ICON_SCALE=1.0
ALIAS_PADDING_L=0
ALIAS_PADDING_R=-7

# plugins
MEDIA_MAX_CHARS=25
