stow:
	@stow --verbose --adopt --restow --target="$$HOME/Library/Application Support" .

unstow:
	@stow --verbose --target="$$HOME/Library/Application Support/Rectangle/" --delete RectangleConfig.json
