return {
  "williamboman/mason.nvim",
  opts = {
    ui = {
      border = "single",
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
      },
    },
    ensure_installed = {
      "black",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "gofumpt",
      "goimports",
      "gopls",
      "hadolint",
      "hclfmt",
      "isort",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "prettierd",
      "python-lsp-server",
      "ruff",
      "shfmt",
      "sqlfluff",
      "sqlfmt",
      "stylua",
      "terraform-ls",
      "tflint",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
