stow:
	@stow --verbose --adopt --restow --target=$$HOME/ .

unstow:
	@stow --verbose --target=$$HOME --delete .

clear-cache:
	@rm -rf $$HOME/.local/share/nvim
	@rm -rf $$HOME/.local/state/nvim/shada/

