#!/bin/sh

export BLACK=0xff181926
export WHITE=0xffe3e8fa
export RED=0xffed8796
export GREEN=0xffa6da95
export BLUE=0xff2780e6
export YELLOW=0xffeed49f
export ORANGE=0xfff5a97f
export MAGENTA=0xffc6a0f6
export GREY=0xff414552
export CYAN=0xff94e2d5
export TRANSPARENT=0x00000000

export LIGHTBLUE=0xff87b3e6
export LIGHTORANGE=0xffe5b987
export LIGHTGREEN=0xffb3e587
export LIGHTPURPLE=0xff8a87e5
export LIGHTRED=0xffe587b3

export BAR_COLOR=$TRANSPARENT
export BACKGROUND_COLOR=$BLACK
export APPLE_ICON_COLOR=$BLUE
export ICON_COLOR=$LIGHTORANGE
export LABEL_COLOR=$LIGHTBLUE
export CHEVRON_COLOR=$LIGHTORANGE

export SPACESET_BACKGROUND_COLOR=$BACKGROUND_COLOR
export SPACE_BACKGROUND_COLOR=$TRANSPARENT
export SPACE_ICON_ACTIVE_COLOR=$ICON_COLOR
export SPACE_ICON_INACTIVE_COLOR=$GREY

export POPUP_BACKGROUND_COLOR=$BAR_COLOR
export POPUP_BORDER_COLOR=$WHITE
export SHADOW_COLOR=$BLACK
