#!/bin/sh
source $HOME/.config/sketchybar/color.sh

ICON_FONT="CommitMono Nerd Font"
ICON_WEIGHT="Bold"
ICON_SIZE="14.0"
ICON_PADDING_LR=9

LABEL_FONT="SF Pro Text"
LABEL_WEIGHT="Bold"
LABEL_SIZE="13.0"
LABEL_PADDING_LR=9

BAR_HEIGHT=32
BAR_POSITION="top"
BAR_PADDING_TOP=4
# NOTCH_WIDTH=188

DEFAULT_PADDING_LR=3
BACKGROUND_HEIGHT=24
BACKGROUND_CORNER_RADIUS=9
BACKGROUND_BORDER_WIDTH=1
