#!/bin/sh
source $HOME/.config/sketchybar/color.sh

APPLE_ICON_SIZE=20
APPLE_Y_OFFSET=2

ICON_FONT="CodeNewRoman Nerd Font"
ICON_WEIGHT="Bold"
ICON_SIZE="14.0"
ICON_PADDING_LR=9

APPICON_FONT="sketchybar-app-font"
APPICON_WEIGHT="Regular"
APPICON_SIZE="14.0"
APPICON_PADDING_LR=9

LABEL_FONT="SF Pro Text"
LABEL_WEIGHT="Bold"
LABEL_SIZE="13.0"
LABEL_PADDING_LR=9

BAR_HEIGHT=32
BAR_POSITION="top"
BAR_PADDING_TOP=4
# NOTCH_WIDTH=188

DEFAULT_PADDING_LR=3
BACKGROUND_HEIGHT=24
BACKGROUND_CORNER_RADIUS=15
BACKGROUND_BORDER_WIDTH=1

SPACESET_BACKGROUND_CORNER_RADIUS=15
SPACE_BACKGROUND_BORDER_WIDTH=0

# plugins
MEDIA_MAX_CHARS=25
