stow:
	@stow --verbose --adopt --restow --target="$$HOME/Library/Application Support/VSCodium/" User

unstow:
	@stow --verbose --target="$$HOME/Library/Application Support/VSCodium/User/" --delete User
