console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = ' '
  foreground = '#2780e6'
  background = 'transparent'

[transient_prompt]
  template = ' '
  foreground = ''
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}#e68d27{{end}}', '{{if eq .Code 0}}#2780e6{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'blue'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} 󱊕 {{ .StashCount }}{{ end }}'
    foreground = 'p:grey'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true
      source = 'cli'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '  {{ .Venv }} {{ .Full }} '
    foreground = '#FFE873'
    background = 'transparent'
    type = 'python'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#539E43'
    background = 'transparent'
    type = 'node'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#79D4FD'
    background = 'transparent'
    type = 'go'

  [[blocks.segments]]
    template = ' 󱁢 {{.WorkspaceName}} '
    foreground = '#5C4EE6'
    background = 'transparent'
    type = 'terraform'

  [[blocks.segments]]
    template = '  {{ .Full }} '
    foreground = '#F66601'
    background = 'transparent'
    type = 'rust'

  [[blocks.segments]]
    style = 'plain'
    template = ''
    foreground = ''
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}#e68d27{{end}}', '{{if eq .Code 0}}#2780e6{{end}}']
