#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
# https://www.youtube.com/watch?v=9U8LCjuQzdc

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = 'gcp'
    style = 'plain'
    foreground = 'transparent'
    background = '#5184F3'
    template = ' 󱇶 {{.Project}} '

  [[blocks.segments]]
    type = 'aws'
    style = 'plain'
    foreground = 'transparent'
    background = '#F58534'
    template = '   {{.Profile}}{{if .Region}}@{{.Region}}{{end}} '


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

# Programming languages version prompt
  [[blocks.segments]]  
    type = "python"
    foreground = "#FFE873"
    background = "transparent"
    template = "  {{ .Venv }} {{ .Full }} "
    # template = " py {{ .Venv }} {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    foreground = "#539E43"
    background = "transparent"
    template = "  {{ .Full }} "
    # template = " node {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    foreground = "#79D4FD"
    background = "transparent"
    template = "  {{ .Full }} "
    # template = " go {{ .Full }} "

  [[blocks.segments]]
    type = "terraform"
    foreground = "#5C4EE6"
    background = "transparent"
    template = " 󱁢 {{.WorkspaceName}} "
    # template = " tf {{.WorkspaceName}} "

  [[blocks.segments]]
    type = "rust"
    foreground = "#F66601"
    background = "transparent"
    template = "  {{ .Full }} "
    # template = " rs {{ .Full }} "
# end of programming languages version prompt

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}cyan{{end}}",
    ]
    background = 'transparent'
    template = '󱗆 ❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}cyan{{end}}",
  ]
  background = 'transparent'
  template = '󱗆 ❯ '

[secondary_prompt]
  foreground = 'cyan'
  background = 'transparent'
  template = '󱗆 ❯❯ '
